version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8081:80"
    depends_on:
      - app
    container_name: shop_nginx

  app:
    build:
        context: .
        dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: shop_app


  db:
      image: mysql:8.0
      restart: always
      volumes:
          - ./tmp/db:/var/lib/mysql
      environment:
          MYSQL_DATABASE: shop
          MYSQL_ROOT_PASSWORD: root
          MYSQL_CHARSET: utf8
          MYSQL_COLLATION: utf8_unicode_ci
          MYSQL_USER: root
      ports:
          - "8101:3306"
      container_name: shop_db


